services:
  bishop:
    image: ghcr.io/ergrassa/fuel-miniapp:latest
    container_name: fuel-miniapp
    env_file:
      - fuel-miniapp.env
    environment:
      - VIRTUAL_HOST=f.zerog.cc
      - LETSENCRYPT_HOST=f.zerog.cc
      - LETSENCRYPT_EMAIL=uzuri@zerog.cc
      - VIRTUAL_PORT=8080
    networks:
      - proxy

networks:
  proxy:
    external: true